insert into authors (id, first_name, last_name) values (1, 'Leland', 'Walding');
insert into authors (id, first_name, last_name) values (2, 'Burgess', 'Zealey');
insert into authors (id, first_name, last_name) values (3, 'Isahella', 'Hardiker');
insert into authors (id, first_name, last_name) values (4, 'Emlynn', 'Colam');
insert into authors (id, first_name, last_name) values (5, 'Itch', 'Dunne');
insert into authors (id, first_name, last_name) values (6, 'Adrien', 'Rimell');
insert into authors (id, first_name, last_name) values (7, 'Mariette', 'Scott');
insert into authors (id, first_name, last_name) values (8, 'Hazlett', 'Pammenter');
insert into authors (id, first_name, last_name) values (9, 'Francoise', 'Fosserd');
insert into authors (id, first_name, last_name) values (10, 'Harper', 'Handrahan');
insert into authors (id, first_name, last_name) values (11, 'Hayden', 'Cuolahan');
insert into authors (id, first_name, last_name) values (12, 'Carmel', 'Feavyour');
insert into authors (id, first_name, last_name) values (13, 'Margery', 'Peyro');
insert into authors (id, first_name, last_name) values (14, 'Beatrix', 'Mousdall');
insert into authors (id, first_name, last_name) values (15, 'Lula', 'Fyall');
insert into authors (id, first_name, last_name) values (16, 'Lorenzo', 'Sheahan');
insert into authors (id, first_name, last_name) values (17, 'Viva', 'Crankshaw');
insert into authors (id, first_name, last_name) values (18, 'Alejoa', 'Boyett');
insert into authors (id, first_name, last_name) values (19, 'Marlowe', 'Beeho');
insert into authors (id, first_name, last_name) values (20, 'Sherri', 'Stacey');
insert into authors (id, first_name, last_name) values (21, 'Glynda', 'Mattityahou');

insert into books (id, price, price_old, title, author_id) values (1, 1099, 1811, 'Voyatouch', 6);
insert into books (id, price, price_old, title, author_id) values (2, 1808, 1917, 'Fixflex', 5);
insert into books (id, price, price_old, title, author_id) values (3, 2605, 2694, 'Zathin', 8);
insert into books (id, price, price_old, title, author_id) values (4, 2077, 2901, 'Konklux', 1);
insert into books (id, price, price_old, title, author_id) values (5, 2501, 1519, 'Holdlamis', 5);
insert into books (id, price, price_old, title, author_id) values (6, 603, 2537, 'Biodex', 11);
insert into books (id, price, price_old, title, author_id) values (7, 701, 1358, 'Stim', 4);
insert into books (id, price, price_old, title, author_id) values (8, 2762, 1158, 'Matsoft', 17);
insert into books (id, price, price_old, title, author_id) values (9, 2414, 2169, 'Voltsillam', 20);
insert into books (id, price, price_old, title, author_id) values (10, 1694, 3048, 'Stim', 12);
insert into books (id, price, price_old, title, author_id) values (11, 2870, 2150, 'Bigtax', 21);
insert into books (id, price, price_old, title, author_id) values (12, 2254, 1645, 'Alpha', 11);
insert into books (id, price, price_old, title, author_id) values (13, 2987, 3681, 'Tresom', 16);
insert into books (id, price, price_old, title, author_id) values (14, 2388, 3436, 'Bamity', 8);
insert into books (id, price, price_old, title, author_id) values (15, 792, 1527, 'Tresom', 11);
insert into books (id, price, price_old, title, author_id) values (16, 1468, 3996, 'Home Ing', 7);
insert into books (id, price, price_old, title, author_id) values (17, 759, 1052, 'Y-Solowarm', 5);
insert into books (id, price, price_old, title, author_id) values (18, 2871, 2280, 'Gembucket', 12);
insert into books (id, price, price_old, title, author_id) values (19, 1607, 3716, 'Stim', 3);
insert into books (id, price, price_old, title, author_id) values (20, 1922, 3060, 'Namfix', 6);
insert into books (id, price, price_old, title, author_id) values (21, 2268, 3799, 'Matsoft', 16);
