insert into tags (id, name) values (1, 'Современная литература');
insert into tags (id, name) values (2, 'Классическая литература');
insert into tags (id, name) values (3, 'Зарубежная литература');
insert into tags (id, name) values (4, 'Фэнтези');
insert into tags (id, name) values (5, 'Английская литература');
insert into tags (id, name) values (6, 'Русская литература');
insert into tags (id, name) values (7, 'Американская литература');
insert into tags (id, name) values (8, 'Фантастика');
insert into tags (id, name) values (9, 'Детская литература');
insert into tags (id, name) values (10, 'Детектив');
insert into tags (id, name) values (11, 'Любовь');
insert into tags (id, name) values (12, 'Мистика');
insert into tags (id, name) values (13, 'Юмор');
insert into tags (id, name) values (14, 'Приключения');
insert into tags (id, name) values (15, 'Сказка');
insert into tags (id, name) values (16, 'Французская литература');
insert into tags (id, name) values (17, 'Художественная литература');
insert into tags (id, name) values (18, 'Англия');
insert into tags (id, name) values (19, 'Психология');
insert into tags (id, name) values (20, 'Философия');
insert into tags (id, name) values (21, 'Экранизировано');
insert into tags (id, name) values (22, 'Любимое');
insert into tags (id, name) values (23, 'Антиутопия');
insert into tags (id, name) values (24, 'Books you must read before you die');
insert into tags (id, name) values (25, 'Роман');
insert into tags (id, name) values (26, 'Франция');
insert into tags (id, name) values (27, 'Дайте две');
insert into tags (id, name) values (28, 'young adult');
insert into tags (id, name) values (29, 'Война');
insert into tags (id, name) values (30, 'История');
insert into tags (id, name) values (31, 'Флэшмоб 2016');
insert into tags (id, name) values (32, 'Детство');
insert into tags (id, name) values (33, 'Жизнь');
insert into tags (id, name) values (34, 'Драма');
insert into tags (id, name) values (35, 'Россия');
insert into tags (id, name) values (36, 'Книжное путешествие');
insert into tags (id, name) values (37, 'Советская литература');
insert into tags (id, name) values (38, 'Триллер');
insert into tags (id, name) values (39, 'Америка');
insert into tags (id, name) values (40, 'Немецкая литература');
insert into tags (id, name) values (41, 'Вампиры');
insert into tags (id, name) values (42, 'Школьная программа');
insert into tags (id, name) values (43, 'Рассказы');
insert into tags (id, name) values (44, 'Магия');
insert into tags (id, name) values (45, 'Дети');
insert into tags (id, name) values (46, 'Русская классика');
insert into tags (id, name) values (47, 'Флэшмоб 2015');
insert into tags (id, name) values (48, 'Биография');
insert into tags (id, name) values (49, 'English');