insert into genre (id, name, parent_id, slug) values (1, 'Лёгкое чтение', null, 'genre-cuf-685');
insert into genre (id, name, parent_id, slug) values (2, 'Фантастика', 1, 'genre-vlw-283');
insert into genre (id, name, parent_id, slug) values (3, 'Боевики', 1, 'genre-myl-873');
insert into genre (id, name, parent_id, slug) values (4, 'Детективы', 1, 'genre-eyt-479');
insert into genre (id, name, parent_id, slug) values (5, 'Триллер', 4, 'genre-jtr-335');
insert into genre (id, name, parent_id, slug) values (6, 'Крутой детектив', 4, 'genre-gcd-201');
insert into genre (id, name, parent_id, slug) values (7, 'Иронический детектив', 4, 'genre-osr-568');
insert into genre (id, name, parent_id, slug) values (8, 'Про маньяков', 4, 'genre-xgm-124');
insert into genre (id, name, parent_id, slug) values (9, 'Шпионский детектив', 4, 'genre-zof-483');
insert into genre (id, name, parent_id, slug) values (10, 'Криминальный детектив', 4, 'genre-gpf-091');
insert into genre (id, name, parent_id, slug) values (11, 'Классический детектив', 4, 'genre-ajx-204');
insert into genre (id, name, parent_id, slug) values (12, 'Политический детектив', 4, 'genre-xls-640');
insert into genre (id, name, parent_id, slug) values (13, 'Фэнтези', 1, 'genre-btx-914');
insert into genre (id, name, parent_id, slug) values (14, 'Романы', 1, 'genre-quq-763');
insert into genre (id, name, parent_id, slug) values (15, 'Ужасы', 1, 'genre-lng-985');
insert into genre (id, name, parent_id, slug) values (16, 'Приключения', 1, 'genre-tmp-136');
insert into genre (id, name, parent_id, slug) values (17, 'Серьёзное чтение', null, 'genre-udi-629');
insert into genre (id, name, parent_id, slug) values (18, 'Биографии', 17, 'genre-cgo-052');
insert into genre (id, name, parent_id, slug) values (19, 'Деловая литература', null, 'genre-dms-719');
insert into genre (id, name, parent_id, slug) values (20, 'Управление экономикой', 19, 'genre-wtv-899');
insert into genre (id, name, parent_id, slug) values (21, 'Карьера', 19, 'genre-neg-751');
insert into genre (id, name, parent_id, slug) values (22, 'Маркетинг', 19, 'genre-rtm-791');
insert into genre (id, name, parent_id, slug) values (23, 'PR', 19, 'genre-ewu-298');
insert into genre (id, name, parent_id, slug) values (24, 'реклама', 19, 'genre-hjl-190');
insert into genre (id, name, parent_id, slug) values (25, 'Финансы', 19, 'genre-bdu-861');
insert into genre (id, name, parent_id, slug) values (26, 'Бизнес-справочники', 19, 'genre-mkr-250');
insert into genre (id, name, parent_id, slug) values (27, 'Личные финансы', 19, 'genre-pna-295');
insert into genre (id, name, parent_id, slug) values (28, 'Менеджмент', 19, 'genre-dyu-537');
insert into genre (id, name, parent_id, slug) values (29, 'Зарубежная деловая литература', 19, 'genre-tlx-538');
insert into genre (id, name, parent_id, slug) values (30, 'Личная эффективность', 19, 'genre-hnm-050');
insert into genre (id, name, parent_id, slug) values (31, 'Тайм-менеджмент', 19, 'genre-wat-730');
insert into genre (id, name, parent_id, slug) values (32, 'Малый бизнес', 19, 'genre-qhs-167');
insert into genre (id, name, parent_id, slug) values (33, 'Продажи', 19, 'genre-ydl-964');
insert into genre (id, name, parent_id, slug) values (34, 'Стартапы и создание бизнеса', 19, 'genre-vki-566');
insert into genre (id, name, parent_id, slug) values (35, 'Корпоративная культура', 19, 'genre-dab-558');
insert into genre (id, name, parent_id, slug) values (36, 'Банковское дело', 19, 'genre-jhp-614');
insert into genre (id, name, parent_id, slug) values (37, 'Логистика', 19, 'genre-avp-666');
insert into genre (id, name, parent_id, slug) values (38, 'Недвижимость', 19, 'genre-wja-622');
insert into genre (id, name, parent_id, slug) values (39, 'Интернет-бизнес', 19, 'genre-gdv-161');
insert into genre (id, name, parent_id, slug) values (40, 'Ораторское искусство/риторика', 19, 'genre-rsp-165');
insert into genre (id, name, parent_id, slug) values (41, 'Привлечение клиентов и лояльность', 19, 'genre-xqz-997');
insert into genre (id, name, parent_id, slug) values (42, 'Делопроизводство', 19, 'genre-xda-261');
insert into genre (id, name, parent_id, slug) values (43, 'Переговоры', 19, 'genre-owf-875');
insert into genre (id, name, parent_id, slug) values (44, 'Государственное и муниципальное управление', 19, 'genre-psm-546');
insert into genre (id, name, parent_id, slug) values (45, 'политическое управление', 19, 'genre-fha-648');
insert into genre (id, name, parent_id, slug) values (46, 'О бизнесе популярно', 19, 'genre-eya-176');
insert into genre (id, name, parent_id, slug) values (47, 'Ценные бумаги/инвестиции', 19, 'genre-rpe-581');
insert into genre (id, name, parent_id, slug) values (48, 'Бухучет/налогообложение/аудит', 19, 'genre-mye-184');
insert into genre (id, name, parent_id, slug) values (49, 'Российская практика', 19, 'genre-zwv-300');
insert into genre (id, name, parent_id, slug) values (50, 'Истории успеха', 19, 'genre-qhh-734');
insert into genre (id, name, parent_id, slug) values (51, 'Интернет-маркетинг', 19, 'genre-lwi-014');
insert into genre (id, name, parent_id, slug) values (52, 'Лидерство', 19, 'genre-dji-631');
insert into genre (id, name, parent_id, slug) values (53, 'Проектный менеджмент', 19, 'genre-esj-933');
insert into genre (id, name, parent_id, slug) values (54, 'Управление качеством', 19, 'genre-rqz-571');
insert into genre (id, name, parent_id, slug) values (55, 'Финансовый менеджмент', 19, 'genre-muy-592');
insert into genre (id, name, parent_id, slug) values (56, 'Управление персоналом', 19, 'genre-gbf-408');
insert into genre (id, name, parent_id, slug) values (57, 'Бизнес-процессы', 19, 'genre-hhs-844');
insert into genre (id, name, parent_id, slug) values (58, 'Управление бизнесом', 19, 'genre-hcu-294');
insert into genre (id, name, parent_id, slug) values (59, 'Драматургия', null, 'genre-syl-399');
insert into genre (id, name, parent_id, slug) values (60, 'Античная драма', 59, 'genre-hxu-231');
insert into genre (id, name, parent_id, slug) values (61, 'Комедия', 59, 'genre-nex-076');
insert into genre (id, name, parent_id, slug) values (62, 'Сценарий', 59, 'genre-xrq-997');
insert into genre (id, name, parent_id, slug) values (63, 'Драма/пьеса', 59, 'genre-auc-109');